# Generated by Django 4.1 on 2022-09-04 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=20, unique=True)),
                ("text", models.CharField(max_length=200)),
                ("date_created", models.DateField(default="2022-09-04")),
                ("date_updated", models.DateField(default="")),
                ("archive", models.BooleanField(default=False)),
                (
                    "sharedwith",
                    models.ManyToManyField(
                        blank=True, related_name="shared", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
