# Generated by Django 4.1.1 on 2022-09-16 11:23
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="sharedwith",
            field=models.ManyToManyField(
                blank=True, related_name="shared_with", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="notes", to="notes.tag"
            ),
        ),
    ]
