# Generated by Django 4.1.1 on 2022-09-08 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_alter_noteversion_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date_updated",
            field=models.DateField(default="2022-09-08"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="note_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="notes.note",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="date_created",
            field=models.DateField(default="2022-09-08"),
        ),
        migrations.AlterField(
            model_name="noteversion",
            name="date_created",
            field=models.DateField(default="2022-09-08"),
        ),
    ]
