# Generated by Django 4.1.1 on 2022-09-09 09:51
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_alter_comment_date_updated_alter_comment_note_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date_updated",
            field=models.DateField(default="2022-09-09"),
        ),
        migrations.AlterField(
            model_name="note",
            name="date_created",
            field=models.DateField(default="2022-09-09"),
        ),
        migrations.AlterField(
            model_name="noteversion",
            name="date_created",
            field=models.DateField(default="2022-09-09"),
        ),
    ]
