# Generated by Django 4.1.1 on 2022-09-10 16:52
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notes", "0005_alter_comment_date_updated_alter_note_date_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date_created",
            field=models.DateField(default="2022-09-10"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date_updated",
            field=models.DateField(default="2022-09-10"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="date_created",
            field=models.DateField(default="2022-09-10"),
        ),
        migrations.AlterField(
            model_name="noteversion",
            name="date_created",
            field=models.DateField(default="2022-09-10"),
        ),
    ]
