# Generated by Django 4.1 on 2022-09-12 09:13
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notes", "0006_alter_comment_date_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date_created",
            field=models.DateField(default="2022-09-12"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date_updated",
            field=models.DateField(default="2022-09-12"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="note_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="notes.note",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="date_created",
            field=models.DateField(default="2022-09-12"),
        ),
        migrations.AlterField(
            model_name="note",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="noteversion",
            name="date_created",
            field=models.DateField(default="2022-09-12"),
        ),
        migrations.AlterField(
            model_name="noteversion",
            name="edited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="noteversion",
            name="note_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="notes.note"
            ),
        ),
    ]
