# Generated by Django 4.1 on 2022-09-13 15:45
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0007_alter_comment_date_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="noteversion",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
