# Generated by Django 4.1 on 2022-09-13 15:56
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0008_alter_comment_date_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="note_id",
            new_name="note",
        ),
        migrations.RenameField(
            model_name="noteversion",
            old_name="note_id",
            new_name="note",
        ),
    ]
