# Generated by Django 4.1.1 on 2022-09-14 08:41
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0009_rename_note_id_comment_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="notes.note",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="note",
            name="text",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(default="", max_length=31),
        ),
        migrations.AlterField(
            model_name="noteversion",
            name="text",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="noteversion",
            name="title",
            field=models.CharField(default="", max_length=31),
        ),
    ]
